# Deployment para Server1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server1
  template:
    metadata:
      labels:
        app: server1
    spec:
      containers:
      - name: server1
        image: httpd:latest
        ports:
        - containerPort: 80
---
# Service para Server1
apiVersion: v1
kind: Service
metadata:
  name: server1-service
spec:
  type: NodePort
  selector:
    app: server1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
# Deployment para Server2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server2
  template:
    metadata:
      labels:
        app: server2
    spec:
      containers:
      - name: server2
        image: httpd:latest
        ports:
        - containerPort: 80
---
# Service para Server2
apiVersion: v1
kind: Service
metadata:
  name: server2-service
spec:
  type: NodePort
  selector:
    app: server2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
# Deployment para Server3
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server3
  template:
    metadata:
      labels:
        app: server3
    spec:
      containers:
      - name: server3
        image: httpd:latest
        ports:
        - containerPort: 80
---
# Service para Server3
apiVersion: v1
kind: Service
metadata:
  name: server3-service
spec:
  type: NodePort
  selector:
    app: server3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-curl-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-curl
  template:
    metadata:
      labels:
        app: ubuntu-curl
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: ["sleep", "infinity"]  # Para mantener el Pod en ejecución
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-curl-service
spec:
  type: NodePort
  selector:
    app: ubuntu-curl
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
