{{- $root := . -}}  # Esta es la línea clave para mantener una referencia al ámbito global.
{{- range list "server1" "server2" "server3" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ . }}
  template:
    metadata:
      labels:
        app: {{ . }}
    spec:
      containers:
        - name: {{ . }}
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ . }}-service
spec:
  type: NodePort
  selector:
    app: {{ . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ index $root.Values.nodePorts . }}
{{- end }}
